export const allSuggestions = [
  // General Navigation
  "Settings",
  "Go to Settings",
  "open Settings",
  "Profile",
  "go to Profile",
  "Open Profile",
  "Order",
  "My Order",
  "Track My Order",
  "Track Order",
  "View Order History",
  "View My Order History",
  "View Order History",
  "Search for Products",
  "Explore Categories",
  "Help",
  "Help Center",
  "Map",
  "store",
  "view store",
  "Customer Support",
  "Contact Customer Support",
  "Check Shipping Policies",
  "Terms and Conditions",
  "View Terms and Conditions",
  "Privacy Policy",
  "View Privacy Policy",

  // Product-Specific Searches
  "Statues",
  "Sculptures",
  "Buddha Statues",
  "Search for Buddha Statues",
  "Find Buddha Statues",
  "Ganesha Sculptures",
  "Find Ganesha Sculptures",
  "Lakshmi",
  "Lakshmi Idols",
  "Shop for Lakshmi Idols",
  "Saraswati",
  "Saraswati Statues",
  "Explore Saraswati Statues",
  "Shiva",
  "Shiva Lingam",
  "Buy a Shiva Lingam",
  "Find Shiva Lingam",
  "Handcrafted",
  "Stupas",
  "Handcrafted Stupas",
  "Find Handcrafted Stupas",
  "Wooden Sculptures",
  "Buy Wooden Sculptures",
  "Metal Statues",
  "Search for Metal Statues",
  "Art",
  "Wall Art",
  "Nepalese Wall Art",
  "Explore Nepalese Wall Art",
  "Buy Meditation Bowls",
  "Shop for Singing Bowls",
  "Find Bronze Bells",
  "Explore Stone Sculptures",
  "Buy Himalayan Incense",
  "Ritual Umbrellas",
  "Search for Ritual Umbrellas",
  "Shop for Decorative Paintings",

  // Ritual and Spiritual Materials
  "Pooja Thalis",
  "Search for Pooja Thalis",
  "Lamps",
  "Diya Lamps",
  "Buy Diya Lamps",
  "Prayer Beads",
  "Find Prayer Beads",
  "Flags",
  "Tibetan Prayer Flags",
  "Explore Tibetan Prayer Flags",
  "Damaru Drums",
  "Buy Damaru Drums",
  "Search for Damaru Drums",
  "Cushions",
  "Meditation Cushions",
  "Buy Meditation Cushions",
  "Sand Mandalas",
  "Explore Sand Mandalas",
  "Altar Accessories",
  "Find Altar Accessories",
  "Texts",
  "Ritual Texts",
  "Shop for Ritual Texts",
  "Buy Mantra Scrolls",
  "Artifacts",
  "Gilded Artifacts",
  "Explore Gilded Artifacts",
  "Sacred Yantras",
  "Find Sacred Yantras",
  "Holy Water Containers",
  "Buy Holy Water Containers",

  // Cultural and Artistic Products
  "Search for Mandala Art",
  "Shop for Traditional Textiles",
  "Find Nepalese Tapestries",
  "Explore Tribal Jewelry",
  "Buy Cultural Masks",
  "Search for Handwoven Rugs",
  "Shop for Eco-Friendly Gifts",

  // User Actions
  "Wishlist",
  "My Wishlist",
  "View My Wishlist",
  "Add to Favorites",
  "Remove from Wishlist",
  "Cart",
  "Add to Cart",
  "Remove from Cart",
  "Proceed to Checkout",
  "Apply a Discount Code",
  "View Payment Options",
  "Update My Address",
  "Update Profile Information",
  "Check Order Status",
  "Request a Refund",
  "Cancel My Order",

  // Special Offers and Promotions
  "Check Today's Deals",
  "Explore Seasonal Offers",
  "Shop Under $50",
  "Find Free Shipping Products",
  "Discover Limited Edition Items",
  "Search for Clearance Sales",

  // Guided Experiences
  "Get Recommendations for Beginners",
  "Find Popular Spiritual Gifts",
  "Explore Top-Rated Statues",
  "Learn About Buddha Statues",
  "Read Reviews on Sculptures",
  "Discover New Arrivals in Statues",
  "Find Rare Collectibles",

  // Inspiration and Ideas
  "Search for Meditation Room Decor",
  "Explore Temple Decorations",
  "Find Gifts for Spiritual Seekers",
  "Shop for Housewarming Gifts",
  "Buy Wedding Gifts with a Spiritual Theme",
  "Find Corporate Gifts for Festivals",

  // Miscellaneous
  "Check Product Availability",
  "Search by Price Range",
  "Search by Material - Brass",
  "Search by Material - Wood",
  "Search by Material - Stone",
  "Shop for Eco-Friendly Products",
  "Explore Art Inspired by Hindu Mythology",
];
