import type { Metadata } from "next";
import localFont from "next/font/local";
import { Provider } from "@/components/provider";
import { SessionProvider } from "next-auth/react";

import { auth } from "@/auth";

import "@/styles/globals.css";

const geistSans = localFont({
  src: "./fonts/AtAero-Medium.woff2",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/AtAero-Semibold.woff2",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()

  return (
    <SessionProvider session={session}>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Provider>{children}</Provider>
        </body>
      </html>
    </SessionProvider>
  );
}
