import type { Chat } from "@/types/notification"

export const mockChats: Chat[] = [
  {
    id: "chat1",
    customer: {
      id: "cust1",
      name: "Sarah Johnson",
      email: "sarah.j@example.com",
      phone: "+1 (555) 123-4567",
    },
    messages: [
      {
        id: "msg1",
        content:
          "Hi, I ordered a dress last week but haven't received any shipping confirmation yet. My order number is #45678.",
        sender: "customer",
        timestamp: new Date(Date.now() - 3600000 * 2).toISOString(),
        read: true,
      },
      {
        id: "msg2",
        content: "Hello Sarah, I'm checking your order status right now. Give me a moment please.",
        sender: "admin",
        timestamp: new Date(Date.now() - 3600000 * 1.5).toISOString(),
        read: true,
      },
      {
        id: "msg3",
        content:
          "I see that your order has been processed and is scheduled for shipping tomorrow. You should receive a confirmation email within 24 hours.",
        sender: "admin",
        timestamp: new Date(Date.now() - 3600000 * 1.4).toISOString(),
        read: true,
      },
      {
        id: "msg4",
        content:
          "Thank you for checking. Can you also confirm if the blue dress is in stock in size medium? I might want to add it to my order.",
        sender: "customer",
        timestamp: new Date(Date.now() - 3600000 * 1).toISOString(),
        read: false,
      },
    ],
    lastMessage: "Thank you for checking. Can you also confirm if the blue dress is in stock in size medium?",
    lastMessageTime: new Date(Date.now() - 3600000 * 1).toISOString(),
    unreadCount: 1,
    status: "active",
    priority: "medium",
    orderNumber: "45678",
  },
  {
    id: "chat2",
    customer: {
      id: "cust2",
      name: "Michael Chen",
      email: "michael.c@example.com",
      phone: "+1 (555) 987-6543",
    },
    messages: [
      {
        id: "msg5",
        content: "I received my order but one of the items is damaged. What should I do?",
        sender: "customer",
        timestamp: new Date(Date.now() - 3600000 * 5).toISOString(),
        read: true,
      },
      {
        id: "msg6",
        content: "I'm sorry to hear that, Michael. Could you please send a photo of the damaged item?",
        sender: "admin",
        timestamp: new Date(Date.now() - 3600000 * 4.8).toISOString(),
        read: true,
      },
      {
        id: "msg7",
        content: "Here's the photo of the damaged headphones. The right earpiece is cracked.",
        sender: "customer",
        timestamp: new Date(Date.now() - 3600000 * 4.5).toISOString(),
        read: true,
      },
    ],
    lastMessage: "Here's the photo of the damaged headphones. The right earpiece is cracked.",
    lastMessageTime: new Date(Date.now() - 3600000 * 4.5).toISOString(),
    unreadCount: 0,
    status: "active",
    priority: "high",
    orderNumber: "78901",
  },
  {
    id: "chat3",
    customer: {
      id: "cust3",
      name: "Emma Rodriguez",
      email: "emma.r@example.com",
      phone: "+1 (555) 234-5678",
    },
    messages: [
      {
        id: "msg8",
        content: "Do you offer international shipping to Spain?",
        sender: "customer",
        timestamp: new Date(Date.now() - 3600000 * 24).toISOString(),
        read: true,
      },
      {
        id: "msg9",
        content:
          "Yes, we do ship to Spain! Shipping typically takes 7-10 business days and costs $25 for standard shipping.",
        sender: "admin",
        timestamp: new Date(Date.now() - 3600000 * 23).toISOString(),
        read: true,
      },
      {
        id: "msg10",
        content: "Great, thank you for the information!",
        sender: "customer",
        timestamp: new Date(Date.now() - 3600000 * 22).toISOString(),
        read: true,
      },
    ],
    lastMessage: "Great, thank you for the information!",
    lastMessageTime: new Date(Date.now() - 3600000 * 22).toISOString(),
    unreadCount: 0,
    status: "closed",
    priority: "low",
  },
  {
    id: "chat4",
    customer: {
      id: "cust4",
      name: "David Wilson",
      email: "david.w@example.com",
      phone: "+1 (555) 345-6789",
    },
    messages: [
      {
        id: "msg11",
        content: "I need to change my delivery address for order #56789. Is that possible?",
        sender: "customer",
        timestamp: new Date(Date.now() - 3600000 * 8).toISOString(),
        read: true,
      },
      {
        id: "msg12",
        content: "Hi David, I can help with that. What's the new address you'd like to use?",
        sender: "admin",
        timestamp: new Date(Date.now() - 3600000 * 7.5).toISOString(),
        read: true,
      },
      {
        id: "msg13",
        content: "Thanks! The new address is 123 Main St, Apt 4B, New York, NY 10001.",
        sender: "customer",
        timestamp: new Date(Date.now() - 3600000 * 7).toISOString(),
        read: false,
      },
    ],
    lastMessage: "Thanks! The new address is 123 Main St, Apt 4B, New York, NY 10001.",
    lastMessageTime: new Date(Date.now() - 3600000 * 7).toISOString(),
    unreadCount: 1,
    status: "active",
    priority: "medium",
    orderNumber: "56789",
  },
  {
    id: "chat5",
    customer: {
      id: "cust5",
      name: "Olivia Taylor",
      email: "olivia.t@example.com",
      phone: "+1 (555) 456-7890",
    },
    messages: [
      {
        id: "msg14",
        content: "Do you have the leather jacket in size small? It shows as out of stock online.",
        sender: "customer",
        timestamp: new Date(Date.now() - 3600000 * 12).toISOString(),
        read: true,
      },
      {
        id: "msg15",
        content: "Let me check our inventory. One moment please.",
        sender: "admin",
        timestamp: new Date(Date.now() - 3600000 * 11.8).toISOString(),
        read: true,
      },
      {
        id: "msg16",
        content: "I've checked and we do have one left in our warehouse. Would you like me to place an order for you?",
        sender: "admin",
        timestamp: new Date(Date.now() - 3600000 * 11.5).toISOString(),
        read: true,
      },
      {
        id: "msg17",
        content: "Yes please! That would be great.",
        sender: "customer",
        timestamp: new Date(Date.now() - 3600000 * 11).toISOString(),
        read: false,
      },
    ],
    lastMessage: "Yes please! That would be great.",
    lastMessageTime: new Date(Date.now() - 3600000 * 11).toISOString(),
    unreadCount: 1,
    status: "active",
    priority: "medium",
  },
  {
    id: "chat6",
    customer: {
      id: "cust6",
      name: "James Brown",
      email: "james.b@example.com",
      phone: "+1 (555) 567-8901",
    },
    messages: [
      {
        id: "msg18",
        content: "I'd like to return an item. What's your return policy?",
        sender: "customer",
        timestamp: new Date(Date.now() - 3600000 * 48).toISOString(),
        read: true,
      },
      {
        id: "msg19",
        content:
          "Our return policy allows returns within 30 days of purchase. You can initiate a return through your account or we can help you here.",
        sender: "admin",
        timestamp: new Date(Date.now() - 3600000 * 47).toISOString(),
        read: true,
      },
      {
        id: "msg20",
        content: "Thanks, I'll initiate it through my account.",
        sender: "customer",
        timestamp: new Date(Date.now() - 3600000 * 46).toISOString(),
        read: true,
      },
    ],
    lastMessage: "Thanks, I'll initiate it through my account.",
    lastMessageTime: new Date(Date.now() - 3600000 * 46).toISOString(),
    unreadCount: 0,
    status: "closed",
    priority: "low",
  },
]

